------------------------------
-- DATA EXPLORATION (EDA)
------------------------------

-- Explore All Countries our customers come from.
SELECT DISTINCT country FROM dim_customers;

-- Explore All Categories
SELECT DISTINCT category, subcategory, product_name FROM dim_products
ORDER BY 1,2,3

-- Find the date of the first and last order
-- How many months of sales are avaiable
SELECT 
	MIN(order_date) AS first_order_date,  
	MAX(order_date) AS last_order_date,
	DATEDIFF(month, MIN(order_date), MAX(order_date)) AS order_range_months
FROM fact_sales

-- Find the youngest and oldest customer
SELECT
	MIN(birthdate) AS oldest_birthdate,
	DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
	MAX(birthdate) AS youngest_birthdate,
	DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age
FROM dim_customers

-- Find the Total Sales
SELECT SUM(sales_amount) AS total_sales FROM fact_sales

-- Find how many items are sold 
SELECT SUM(quantity) AS total_quantity FROM fact_sales

-- Find the average selling price
SELECT AVG(price) AS avg_price FROM fact_sales

-- Find the Total Number of Orders
SELECT COUNT(DISTINCT order_number) AS total_orders FROM fact_sales

-- Find the Total Number of Products
SELECT COUNT(product_key) AS total_products FROM dim_products

-- Find the Total Number of Customers
SELECT COUNT(customer_key) AS total_customers FROM dim_customers 

-- Find the Total Number of Orders that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM fact_sales 

-- Generate a Report that shows all key metrics of the business

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_value FROM fact_sales
UNION ALL
SELECT 'Total Number of Orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM fact_sales
UNION ALL
SELECT 'Total Number of Products' AS measure_name, COUNT(product_key) AS total_products FROM dim_products
UNION ALL
SELECT 'Total Number of Customers' AS measure_name, COUNT(customer_key) AS total_customers FROM dim_customers 

-- Find total customers by countries
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT 
category,
COUNT(product_key) AS total_products
FROM dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is average costs in each category?
SELECT 
category,
AVG(cost) AS avg_costs
FROM dim_products
GROUP BY category
ORDER BY avg_costs DESC

-- What is the total revenue generated for each category?
SELECT 
p.category,
SUM(f.sales_amount) AS total_revenue
FROM fact_sales f
LEFT JOIN dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- What is the total revenue generated by each customer?
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM fact_sales f 
LEFT JOIN dim_customers c 
ON c.customer_key = f.customer_key
GROUP BY 
c.first_name, 
c.customer_key, 
c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of items sold across countries? 
SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM fact_sales f 
LEFT JOIN dim_customers c 
ON c.customer_key = f.customer_key
GROUP BY 
c.country
ORDER BY total_sold_items DESC

-- Which 5 Products generate the highest revenue?
SELECT 
*
FROM (
SELECT 
p.product_name,
SUM(f.sales_amount) AS total_revenue,
ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
FROM fact_sales f
LEFT JOIN dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
)t
WHERE rank_products <= 5


-- What are the 5 worst-performing products in terms of sales?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM fact_sales f
LEFT JOIN dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue 

-- Find the top 10 customers who have generated the highest revenue
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM fact_sales f 
LEFT JOIN dim_customers c 
ON c.customer_key = f.customer_key
GROUP BY 
c.first_name, 
c.customer_key, 
c.last_name
ORDER BY total_revenue DESC


-- The 3 customers with the fewest orders placed
SELECT TOP 3  
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT f.order_number) AS total_orders
FROM fact_sales f 
LEFT JOIN dim_customers c 
ON c.customer_key = f.customer_key
GROUP BY 
c.first_name, 
c.customer_key, 
c.last_name
ORDER BY total_orders ASC

-- Monthly Sales Performance
SELECT
DATETRUNC(month, order_date) AS order_date,
SUM(sales_amount) AS total_sales,
COUNT(DISTINCT customer_key) AS total_customers,
SUM(quantity) as total_quantity
FROM fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month, order_date)
ORDER BY DATETRUNC(month, order_date) DESC

-- Calculate the total sales per month
-- and the running total of sales over time
SELECT 
order_date,
total_sales,
SUM(total_sales) OVER(PARTITION BY order_date ORDER BY order_date) AS running_total_sales,
AVG(avg_price) OVER(PARTITION BY order_date ORDER BY order_date) AS moving_average_price
FROM 
(
SELECT
DATETRUNC(month, order_date) AS order_date,
SUM(sales_amount) AS total_sales,
AVG(price) AS avg_price
FROM fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month, order_date)
)t

/* Analyze the yearly performance of products by comparing their sales to both 
the average sales performance of the product and the previous year's sales */
WITH yearly_product_sales AS (
SELECT
YEAR(f.order_date) AS order_year,
p.product_name,
SUM(f.sales_amount) AS current_sales
FROM fact_sales f 
LEFT JOIN dim_products p
ON f.product_key = p.product_key
WHERE f.order_date IS NOT NULL
GROUP BY 
YEAR(f.order_date),
p.product_name
)
SELECT 
order_year,
product_name,
current_sales,
AVG(current_sales) OVER (PARTITION BY product_name) avg_sales,
current_sales - AVG(current_sales) OVER (PARTITION BY product_name) AS diff_avg,
CASE WHEN current_sales - AVG(current_sales) OVER (PARTITION BY product_name) > 0 THEN 'Above Avg' 
	 WHEN current_sales - AVG(current_sales) OVER (PARTITION BY product_name) < 0 THEN 'Below Avg'
	 ELSE 'Avg'
END avg_change,
LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) py_sales,
current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) AS diff_py,
CASE WHEN current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) > 0 THEN 'Increase' 
	 WHEN current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) < 0 THEN 'Decrease'
	 ELSE 'No Change'
END py_change
FROM yearly_product_sales
ORDER BY product_name, order_year

-- Which categories contribute the most to overall sales?
WITH category_sales AS (
SELECT
category,
SUM(sales_amount) AS total_sales
FROM fact_sales f
LEFT JOIN dim_products p 
ON f.product_key = p.product_key
GROUP BY category
)

SELECT 
category,
total_sales,
SUM(total_sales) OVER () overall_sales,
CONCAT(ROUND(CAST(total_sales AS FlOAT) / SUM(total_sales) OVER () * 100, 2), '%') AS percentage_of_total
FROM category_sales
ORDER BY total_sales DESC

/*Segment products into cost ranges and
count how many products fall into each segment */
WITH product_segments AS (
SELECT
product_key,
product_name,
cost,
CASE WHEN cost < 100 THEN 'Below 100'
	 WHEN cost BETWEEN 100 AND 500 THEN '100-500'
	 WHEN cost BETWEEN 500 AND 1000 THEN '500-1000'
	 ELSE 'Above 1000'
END cost_rage
FROM dim_products)

SELECT 
cost_rage,
COUNT(product_key) AS total_products
FROM product_segments
GROUP BY cost_rage
ORDER BY total_products DESC

/* Group customers into three segments based on their spending behavior:
	VIP — customers with a history of at least 12 months who have spent more than ˆ5,000.
	Regular — customers with a history of at least 12 months who have spent ˆ5,000 or less.
	New — customers with a relationship period of less than 12 months.
And find the total number of customers by each group
*/
WITH customer_spending AS
(
SELECT
c.customer_key,
SUM(f.sales_amount) total_spending,
MIN(order_date) first_order,
MAX(order_date) last_order,
DATEDIFF (month, MIN(order_date), MAX(order_date)) AS lifespan
FROM fact_sales f
LEFT JOIN dim_customers c 
ON f.customer_key = c.customer_key
GROUP BY c.customer_key
)
SELECT 
customer_segment,
COUNT(customer_key) AS total_customers
FROM (
SELECT 
customer_key,
CASE WHEN lifespan >= 12 AND total_spending > 5000 THEN 'VIP'
	 WHEN lifespan >= 12 AND total_spending <= 5000 THEN 'Regular'
	 ELSE 'New'
END customer_segment
FROM customer_spending
)t
GROUP BY customer_segment
ORDER BY total_customers DESC

/*
======================================================================
Customer Report
======================================================================

Purpose:
- This report consolidates key customer metrics and behaviors

Highlights:
1. Gathers essential fields such as names, ages, and transaction details.
2. Segments customers into categories (VIP, Regular, New) and age groups.
3. Aggregates customer-level metrics:
    - total orders
    - total sales
    - total quantity purchased
    - total products
    - lifespan (in months)
4. Calculates valuable KPIs:
    - recency (months since last order)
    - average order value
    - average monthly spend

======================================================================
*/
WITH base_query AS (
SELECT
f.order_number,
f.product_key,
f.order_date,
f.sales_amount,
f.quantity,
c.customer_key,
c.customer_number,
CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
DATEDIFF(year, c.birthdate, GETDATE()) AS age
FROM fact_sales f 
LEFT JOIN dim_customers c
ON c.customer_key = f.customer_key
WHERE order_date IS NOT NULL)

,customer_aggregation  AS (
SELECT 
customer_key,
customer_number,
customer_name,
age,
COUNT(DISTINCT order_number) AS total_orders,
SUM(sales_amount) AS total_sales,
SUM(quantity) AS total_quantity,
COUNT(DISTINCT product_key) AS total_products,
MAX(order_date) AS last_order_date,
DATEDIFF (month, MIN(order_date), MAX(order_date)) AS lifespan
FROM base_query
GROUP BY 
customer_key,
customer_number,
customer_name,
age
)

SELECT 
customer_key,
customer_number,
customer_name,
age,
CASE 
	 WHEN age < 20 THEN 'Under 20'
	 WHEN age BETWEEN 20 AND 29 THEN '20-29'
	 WHEN age BETWEEN 30 AND 39 THEN '30-39'
	 WHEN age BETWEEN 40 AND 49 THEN '40-49'
	 ELSE '50 and above'
END age_group,
CASE WHEN lifespan >= 12 AND total_sales > 5000 THEN 'VIP'
	 WHEN lifespan >= 12 AND total_sales <= 5000 THEN 'Regular'
	 ELSE 'New'
END customer_segment,
last_order_date,
DATEDIFF(month, last_order_date, GETDATE()) AS recency,
total_orders,
total_sales,
total_quantity,
total_products,
lifespan,
CASE WHEN total_orders = 0 THEN 0 
	 ELSE total_sales / total_orders
END AS avg_order_value,
CASE WHEN lifespan = 0 THEN total_sales
	 ELSE total_sales / lifespan
END AS avg_monthly_spend
FROM customer_aggregation

/*
================================================================================
Product Report
================================================================================
Purpose:
  - This report consolidates key product metrics and behaviors.

Highlights:
  1. Gathers essential fields such as product name, category, subcategory, and cost.
  2. Segments products by revenue to identify High-Performers, Mid-Range, or Low-Performers.
  3. Aggregates product-level metrics:
      - total orders
      - total sales
      - total quantity sold
      - total customers (unique)
      - lifespan (in months)
  4. Calculates valuable KPIs:
      - recency (months since last sale)
      - average order revenue (AOR)
      - average monthly revenue
================================================================================
*/
CREATE OR ALTER VIEW report_products AS
WITH base_query AS (
    /* Initial data selection combining products with sales facts.
    Filter out products that have never been sold.
    */
    SELECT
        p.product_key,
        p.product_name,
        p.category,
        p.subcategory,
        p.cost,
        f.order_number,
        f.customer_key,
        f.order_date,
        f.quantity,
        f.sales_amount
    FROM dim_products AS p
    LEFT JOIN fact_sales AS f ON p.product_key = f.product_key
    WHERE f.order_date IS NOT NULL
),

product_aggregations AS ( 
    /* Aggregating metrics at the product level.
    Calculating lifespan as the number of months between first and last sale.
    */
    SELECT
        product_key,
        product_name,
        category,
        subcategory,
        cost,
        COUNT(DISTINCT order_number) AS total_orders,
        SUM(sales_amount)            AS total_sales,
        SUM(quantity)                AS total_quantity,
        COUNT(DISTINCT customer_key) AS total_customers,
        MIN(order_date)              AS first_order_date,
        MAX(order_date)              AS last_order_date,
        -- Added +1 to lifespan to prevent division by zero and account for the starting month
        DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) + 1 AS lifespan
    FROM base_query
    GROUP BY 
        product_key, 
        product_name, 
        category, 
        subcategory, 
        cost
)

/* Final selection with calculated KPIs and product segmentation 
*/
SELECT
    product_key,
    product_name,
    category,
    subcategory,
    cost,
    total_orders,
    total_sales,
    total_quantity,
    total_customers,
    lifespan,
    last_order_date,
    
    -- Segmenting products based on total revenue thresholds
    CASE
        WHEN total_sales > 50000 THEN 'High-Performer'
        WHEN total_sales >= 10000 THEN 'Mid-Range'
        ELSE 'Low-Performer'
    END AS product_segment,

    -- Calculating how many months have passed since the last sale
    DATEDIFF(MONTH, last_order_date, GETDATE()) AS recency_in_months,

    -- Average revenue generated per unique order
    CASE 
        WHEN total_orders = 0 THEN 0 
        ELSE total_sales / total_orders 
    END AS avg_order_revenue,

    -- Average revenue generated per month of the product's lifespan
    CASE 
        WHEN lifespan = 0 THEN total_sales 
        ELSE total_sales / lifespan 
    END AS avg_monthly_revenue

FROM product_aggregations;